Feature/expdat 013
sw21-tug/Team_25 pull request #44
Opened 2021-05-16 18:29 UTC by ChrisFartek

This closes #13.

2021-05-18 22:05 UTC, steschi requested changes
The shareViewTest Testcase does not work for me. I am not sure if it is an issue on my emulator or not. 
![image](https://user-images.githubusercontent.com/8997333/118729242-d1f1e300-b835-11eb-96da-31c3c451998b.png)

2021-05-18 22:05 UTC, steschi commented on app/src/androidTest/java/at/sw21_tug/team_25/expirydates/DetailViewTest.kt
> +import android.content.Context.CLIPBOARD_SERVICE
please remove unused imports

2021-05-18 22:05 UTC, steschi commented on app/src/androidTest/java/at/sw21_tug/team_25/expirydates/DetailViewTest.kt
> +        val appContext = ApplicationProvider.getApplicationContext<Application>()
please remove unused variables

2021-05-18 22:05 UTC, steschi commented on app/src/main/java/at/sw21_tug/team_25/expirydates/ui/detailview/ui/DetailViewActivity.kt
> +                    } else if (Util.getLanguage(activity as MainActivity) == Locale("ru")) {
please move all hardcoded strings which need translation to the strings.xml

Details on how to store Format-Strings in resource files can be found here: https://developer.android.com/guide/topics/resources/string-resource#FormattingAndStyling

2021-05-19 15:32 UTC, florianmarcher approved these changes
all tests passed

2021-05-19 15:34 UTC, merged